version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mkdir build
      - mkdir build/sitefiles
      - mkdir build/scripts
      - cp -R sitefiles/* build/sitefiles/
      - cp -R scripts/ build/scripts/
      - zip -qr build-output.zip build/*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build-output.zip