version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mkdir build
      - cp -R sitefiles/* build/
      - cd build/
      - zip -qr build-output.zip ./*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build-output.zip